baseURL = "https://tooltown.void.cold.at/"
locale = "en_US"
title = "Tooltown"
publishDir = "static"
staticDir = "site-static"
disableKinds = ["taxonomy", "term", "rss"]

[params]
description = "A focused collection of tools I develop, with clear jobs and direct access."

[[module.mounts]]
source = "content"
target = "content"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "tools"
target = "assets/tools"
